### ISSUE TITLE
Complex coupling between Shell implementation and its Controller

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#107]
Inspecting an `Impl::Shell` instance from running the executable `wabur`:
```diff
#<WAB::Impl::Shell:0x2596830
  [...]
+ @controllers={nil=>#<BasicController:0x2595450 @shell=#<WAB::Impl::Shell:0x2596830 ...>>},
  [...]>>
```
Inspecting the registered controller within the `Impl::Shell` instance:
```diff
#<BasicController:0x2895810
  @shell=#<WAB::Impl::Shell:0x2896de8 @path_pos=1, @model=#<WAB::Impl::Model:0x2896b00 
  @dir=nil, @cnt=0, @map={}, @lock=#<Thread::Mutex:0x28968f0>>, @type_key="kind", 
  @verbose=nil, @http_dir=".", @http_port=6363,
+ @controllers={nil=>#<BasicController:0x2895810 ...>}[...]>>>
```

**Comment by ohler55** [comment]
What is the issue here? I'm guessing it has something to do with the printout but not sure what since not all is shown.

**Comment by ashmaroli** [comment]
The issue here is that the `Impl::Shell` has an attribute that store a `Controller` instance which has an attribute that stores the previously mentioned `Impl::Shell` instance which again stores the same Controller instance.................

**Comment by ohler55** [comment]
There is nothing wrong with having the references. They are needed. Is the issue that to_s or inspect does not look pretty enough?

**Comment by ashmaroli** [comment]
nope.. pretty inspect is not the issue here.. but rather that the Controller and Shell "know each other" in sort of a loop..

If its a necessity, then it fine. This can be closed right away.. But if that can be made a linear behaviour, then IMO, we should..

**Comment by ohler55** [comment]
It can't given the nature of the system. Shell passes HTTP requests to controllers so that reference is needed and Controllers send model requests to the Shell so that is needed.

**Comment by ashmaroli** [comment]
No longer a valid issue then..
