### ISSUE TITLE
ERROR:  Could not find a valid gem 'wabur' (>= 0) in any repository

### ISSUE THREAD

**Issue by ohaddahan** [ohler55/wabur#122]
Not to sound like a pain in the ass , but where do I get `wabur` Gem from?
(while assuming that the a simple `gem install` is available)

> The wabur Runner is used for this lesson. To start the Runner, the wabur gem must be installed or the wabur source must be available.

`gem install wabur` fails , and trying [http://www.wab.systems/](url) end in a  `Coming soon` page.

`WABuR is a Web Application Builder using Ruby. Releases and additional information can be found at http://www.wab.systems.`

Trying to rub `bin/wabur` fails on :
`require': cannot load such file -- wab  (LoadError)

While `wab` checking if `wab` is the correct Gem name , turned out as false.

> ERROR:  Could not find a valid gem 'wab' (>= 0) in any repository

**Comment by ohler55** [comment]
You are a step ahead. I wrote the tutorial to double as a requirements doc for the new JavaScript front end that I am working on now. The tutorial is not ready for use yet.

There is an examples/sample that does work but the UI portion will become out of date soon. All the backend stuff is pretty stable at this point though.

gem install wabur should work but it is out of date. I would recommend pulling from GitHub only until next month. By then the wab.systems will be in c=lace as well.

The most recent develop branch on GitHub includes the bin/wabur. Not that the develop branch is the default branch on GitHub.

I'm very glad to have you be a PITA. Its good to know someone is looking at WABuR.

**Comment by ohler55** [comment]
https://rubygems.org/gems/wabur for the gem in the future. For now GitHub.

**Comment by ohaddahan** [comment]
@ohler55 
`wab.rb` need to use `require_relative` instead of `require`.
That fixed the issue (I already cloned GitHub from the beginning , but preferred using `gem install` if possible).

`bin/wabur` was still giving me some issues so I launched it with `-I` and it resolved it :

> lesson-1/../../bin/wabur -I ../../lib --base app --controller WAB::OpenController --ui UI::Entry

This brought up a new issue:
`wabur_test/wabur/lib/wab/impl/configuration.rb:28:in `initialize': invalid option: --controller (OptionParser::InvalidOption)`

Which I guess is expected since as you said the documentation isn't up to date.

**Comment by ohler55** [comment]
Expected at this stage. If you want to see something right away, the Examples/sample is really the way to go.

**Comment by ohaddahan** [comment]
Already ran it , but it's a little low on content.
I'll try deriving from the tutorial lessons and merge them with the sample to get things rolling.

**Comment by ohler55** [comment]
To explain the most significant differences between the tutorial which outlines the future and the sample is that the conf.js in the sample will be served to the UI from a controller on a URL path of /v1/ui. The other big difference is that I've started with ES6 instead of ES5 for Javascript. I'm trying to keep it simple and agnostic of package manager and other tools but babel does not like to handle simple cases.

**Comment by ohler55** [comment]
BTW, I just pushed a new 0.4.0 wabur gem.
