### ISSUE TITLE
Implement a Proxy

### ISSUE THREAD

**Issue by ohler55** [ohler55/wabur#127]
Implement a proxy that serves files in the asset directory of a project. It should only serve hard coded files/data if a file is not present.

**Comment by ashmaroli** [comment]
Also consider bundling these "assets" in the rubygem itself and serve them when a user first "generates" a WAB App workspace

**Comment by ohler55** [comment]
Added `export` to gem and a WAB.get_export function. wabur and opo-rub both support the alternative source.
