### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#131]
Found a few bugs in the new UI code. Should've pointed them out while reviewing the PR.. my bad.

- checkboxes do not have a `readonly` attribute
  ```
  elsif value.is_a?(TrueClass)
    input = %{<input class="form-field" id="#{path}.#{id}" type="checkbox" checked #{readonly}>}
  elsif value.is_a?(FalseClass)
    input = %{<input class="form-field" id="#{path}.#{id}" type="checkbox" #{readonly}>}
  ```
- `readonly` leaked into input value
   ```
   input = %{<input class="form-field" id="#{path}.#{id}" type="number" value="#{value} #{readonly}">}`
   ```
- `./view/ui/styles` doesn't seem to be used

**Comment by ohler55** [comment]
Checkboxes now use `disabled="disabled"`

`ui/styles` now used by build scripts.

number input fixed.
