### ISSUE TITLE
Allow configuring Ruby runner JSON API indentation

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#138]
While it is already possible to configure indentation for JSON from OpO runners, Ruby runner `wabur` doesn't seem to support this functionality.

**Comment by ohler55** [comment]
The question is, does it need to. Is there a reason to send formatted JSON or is tighter better since it is only a format for transfer.

**Comment by ashmaroli** [comment]
> does it need to

It could be such that the JSON is tighter in production whereas in development, its pretty-formatted..
But having an option is always better.

If its possible in OpO based runners, it should be easily ported to Ruby runners as well, right?

**Comment by ohler55** [comment]
Being an option in OpO does not make it easy, or harder to add to the Ruby runner. They are completely different. Having said that, it is not difficult to add to the Ruby runner either. Its more a matter of if we want to add it.

**Comment by ashmaroli** [comment]
:) I would like have such an option..

**Comment by ohler55** [comment]
ok
