### ISSUE TITLE
Allow determining library version with conventional switches

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#156]
Currently, `wabur` doesn't recognize a `--version` option and `-v` is used to adjust the runner verbosity.

  - It'd be better to reassign `-v` to output library version along the lines of `ruby -v` and `rails -v` and assign `-V` for adjusting verbosity.
  - The alternative would be to continue as is with `-v` for verbosity and assign just `--version` for outputting library version.

**Comment by ohler55** [comment]
Completed with PR #161
