### ISSUE TITLE
Use of backtick isn't safe

### ISSUE THREAD

**Issue by ohaddahan** [ohler55/wabur#168]
https://github.com/ohler55/wabur/blob/bab28d05e747d2d2d870e1d8c8e5b4b527a62740/lib/wab/impl/init.rb#L137

Using backtick isn't recommended , for several reasons:

1. Alias for `cp` might cause unexpected behaviour.
2. If the filepath need to get escaped , for example I had a path with spaces and using backticks didn't escape it properly.

I would recommend using Ruby copying interface since it's more robust and the number of file copying done is small , no reason to try and optimize there.

It will require changing `out.empty?` to `out.nil?` and adding an exception handling incase of error.

**Comment by ohler55** [comment]
I think it makes sense to use the Ruby copy FileUtils copy method but not for the reasons given. It makes sense in regard to platform compatibility. The reason the points given are not valid are:

  1. This is used in a developer script. If the use aliases `cp` to something harmful for their own computer they have elected to do that so it is their own problem. Maybe with sanity but that is another issue entirely.
  2. A simple set of quotes would solve this but I agree with the conclusion that the FileUtilis is a better choice.
