### ISSUE TITLE
Support the Rack API

### ISSUE THREAD

**Issue by ohler55** [ohler55/wabur#176]
Add support for the Rack API.

Some thought needs to go into this to figure out the best way to support the API. Is it an alternative or a layer. If a layer, does it reside between the server and the Ruby code or between the WAB::Controller and subclassed controllers?

**Comment by ashmaroli** [comment]
What are the possible use-cases that would benefit with this..?

**Comment by ohler55** [comment]
It seems the Rack API is use for chaining processing steps. So the Controller could accepts a `call()` and then allow other apps to form a chain of steps before completing the returned JSON. I need to dig into it a bit more but this is an approach used by Hanami and is supported by WEBrick, Sinatra, and other HTTP server APIs. Done correctly it should allow 'plugin' of other gems.

**Comment by ohler55** [comment]
Completed
