### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by ohler55** [ohler55/wabur#29]
Hook into coveralls.io for test coverage reporting.

**Comment by ashmaroli** [comment]
Its pretty simple.. sign in with your GitHub creds and select this repo..

**Comment by ohler55** [comment]
Yeah, figured it would be easy. Just wanted to leave a note here as a reminder.

**Comment by ashmaroli** [comment]
I suggest disabling `LEAVE COMMENTS` in `Settings> Pull Requests`

![coveralls](https://user-images.githubusercontent.com/12479464/29495804-fd920a9a-85e3-11e7-8d25-f50bd70d8abc.png)

**Comment by ohler55** [comment]
ok

**Comment by ohler55** [comment]
Didn't work the way we wanted it to. Doesn't like forks and failed to pick up obvious covered case in non-forked.
