### ISSUE TITLE
Same method called with same argument by different branches of conditional

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#48]
There seems to be a typo in the `#detect` method for `WAB::Impl::Data`.
Both branches of the conditional calls **`detect_hash(@root)`**

```ruby
def detect()
  if @root.is_a?(Hash)
    detect_hash(@root)
  elsif @root.is_a?(Array)
    detect_hash(@root)
  end
end
```
My guess is that the `elsif` branch ought be calling the private method **`detect_array`** instead..

**Comment by ohler55** [comment]
You are correct, it should be detect_array.
